language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-9.2.5.0

gemfile:
  - gemfiles/rails_5.0/Gemfile.rest-client.1.8
  - gemfiles/rails_5.0/Gemfile.rest-client.2.0
  - gemfiles/rails_5.0/Gemfile.rest-client.2.1

  - gemfiles/rails_5.1/Gemfile.rest-client.1.8
  - gemfiles/rails_5.1/Gemfile.rest-client.2.0
  - gemfiles/rails_5.1/Gemfile.rest-client.2.1

  - gemfiles/rails_5.2/Gemfile.rest-client.1.8
  - gemfiles/rails_5.2/Gemfile.rest-client.2.0
  - gemfiles/rails_5.2/Gemfile.rest-client.2.1

cache: bundler

sudo: false

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
